version: '3.1'
services:
  app:
    container_name: spring-reddit-docker-compose
    image: springboot-reddit
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=test_db 
      - MYSQL_USER=admin 
      - MYSQL_PASSWORD=admin