version: '3.8'
services:
  mongo-express:
    image: mongo-express
    networks: 
    - mongodb-network
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb # mongodb container name

networks:
  mongodb-network:
    external: true