apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-reddit-clone-deployment
spec:
  selector:
    matchLabels:
      app: spring-reddit-clone
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-reddit-clone
    spec:
      containers:
        - name: spring-reddit-clone
          image: dimuthu256/spring-reddit-clone:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: spring-reddit-clone-service
spec:
  selector:
    app: spring-reddit-clone
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30160